### ISSUE TITLE
iOS 14 Error

### ISSUE THREAD

**Issue by dmholmes** [fatbobman/NavigationViewKit#2]
My app works correctly with NavigationViewKit in iOS 15 but crashes with the following in iOS 14 simulator and device. App works in iOS 14 without NavigationViewKit. Anything I can try to resolve?

dyld: Symbol not found: _$s6_Body27SwiftUI19NavigationViewStylePTl
  Referenced from: /private/var/containers/Bundle/Application/AFD042A3-C3E5-490B-9E04-D293FE66EFCD/TheApp.app/TheApp
  Expected in: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 in /private/var/containers/Bundle/Application/AFD042A3-C3E5-490B-9E04-D293FE66EFCD/TheApp.app/TheApp
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by fatbobman** [comment]
Hello.
I don't know what version of Xcode and macOS you have?
I was previously on Big Sur + Xcode 12 and it was working fine on iOS 14.
I just got the same error you mentioned under Xcode 13 + Monterey. Since Xcode 12 doesn't run under Monterey, I have no way to reconfirm if the code will have problems under iOS 14 when using Xcode 12.

The current problem occurs with a couple of NavigationViewStyle extensions. If you don't need to use these custom extensions. If you only need to use NavigationViewManager, you can just copy NavigationViewManger.swift and NavigationViewMangerMisc.swift to your project.

**Comment by dmholmes** [comment]
Thanks for the help @fatbobman. Yes I only need to use the navigation manager for .popToRoot(). I uninstalled the package and copied the 2 files into my project (Xcode 13.1, iOS 14 deployment target, macOS 11.6.1). NavigationViewManager is failing to compile:

- 193: Value of type 'AllowPopToRoot.Content' (aka '_ViewModifier_Content<AllowPopToRoot>') has no member 'introspectNavigationController'
- 196: Cannot infer key path type from context; consider explicitly specifying a root type

**Comment by fatbobman** [comment]
you need to add https://github.com/siteline/SwiftUI-Introspect package and import it in navigationgKit files

**Comment by dmholmes** [comment]
That did the trick, thank you!
